# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('current_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='work_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.work_location'),
        ),
    ]
